name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository 에 올린 파일들을 불러오기
        uses: actions/checkout@v4 # 라이브러리 repository 에 있는 코드들을 불러오는 라이브러리

      - name: JDK 17 버전 설치
        uses: actions/setup-java@v4 # jdk 17 을 설치하는 라이브러리
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES}}" > ./src/main/resources/application.yml # 이렇게 하면 끝

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOP.jar ./project.jar

      # 빌드 파일을 SCP 파일 로 EC2 에 전송하기
      - name: SCP 로 EC2 에 빌드 된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/instagram-server/tobe # SCP 로 해당 경로로 project.jar 옮기기
           
      - name: SSH(원격 접속)으로 EC2에 접속 하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm - rf /home/ubuntu/instagram-server/current
            mkdir /home/ubuntu/instargram-server/current
            mv /home/ubuntu/instargram-server/tobe/project.jar /home/ubuntu/instargram-server/current/project.jar
            cd /home/ubuntu/instargram-server/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar project.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/instagram-server/tobe 
