name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      # 현재 저장소 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      #  Gradle wrapper 실행권한 추가 (윈도우 to 리눅스 환경일 때 필수임)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # (3) Spring Boot 빌드 (테스트 제외)
      - name: Build Spring Boot Project
        run: ./gradlew clean build -x test

      # (4) EC2 접속 후 원격 배포 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/ci.cd-practices
            git pull origin main
            ./gradlew clean build -x test
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > output.log 2>&1 &
