name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 에 올린 파일들을 불러오기
        uses: actions/checkout@v4 # 라이브러리 repository 에 있는 코드들을 불러오는 라이브러리

      - name: JDK 17 버전 설치
        uses: actions/setup-java@v4 # jdk 17 을 설치하는 라이브러리
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES}}" > ./src/main/resources/application.yml # 이렇게 하면 끝

      - name: permission
        run: chmod +x gradlew

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar
      # s3 에 전송하려면 압축이 되어있어야 한다.
      - name: 압축하기
        run: tar -czvf $GITHUB_SHA.tar.gz project.jar appspec.yml scripts
      # S3 와 CodeDeploy 에 접근 허용
      - name: AWS Resource 에 접근 할수있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: S3에 프로젝트 폴더 업로드하기
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://instagram-server/$GITHUB_SHA.tar.gz
      # DeployCode 에 애플리케이션을 만들고, 배포 그룹을 만들었다. 배포를 생성하는 명령어이다
      # 어떤 애플리케이션에서 생성할것인가
      # 어떤방식으로 배포를 생성할것인가 ? AllAtOnce 한번에
      #어떤 배포그룹에 배포를 할것인가
      # s3 버킷에서 나와서 이런 확장자로 줄것이다
      - name: CodeDeploy 를 활용해 EC2에 프로젝트 코드를 배포하라고 명령
        run: aws deploy create-deployment --application-name instagram-server --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name Production-Group --s3-location bucket=instagram-server,bundleType=tgz,key=$GITHUB_SHA.tar.gz